### ISSUE TITLE
[to-do]  add model persistence

### ISSUE THREAD

**Issue by Sing-Li** [llmshare/llmlocalmgr#9]
- [ ] convert `buildMLCLocalConfig` to actually populate the database via the model
- [ ] modify all downstream code to use the model layer only
- [ ] add a cli command `updatedb` that will re-parse the mlc-ai page and rebuild the model/database
